name: Build 
on: [push, pull_request]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Maven Library build 
        run: mvn -B test --cov .
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t -f ${CODECOV_TOKEN}

