name: Build and Release SDK
on:
  push:
    branches:
      - main
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build and Update Version
        run: |
          ./mvnw clean install
          ./mvnw versions:set -DnewVersion=1.0.0-SNAPSHOT
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository"
      - name: sbt to Maven Central
        uses: cosmincatalin/sbt-to-maven-central@v1.0.6


